//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PatientDemographicsEntities : DbContext
    {
        public PatientDemographicsEntities()
            : base("name=PatientDemographicsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PatientDetail> PatientDetails { get; set; }
    
        public virtual int usersp_InsertPersonalDetails(string xmlInfo)
        {
            var xmlInfoParameter = xmlInfo != null ?
                new ObjectParameter("xmlInfo", xmlInfo) :
                new ObjectParameter("xmlInfo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usersp_InsertPersonalDetails", xmlInfoParameter);
        }
    }
}
